version: '3.1'
services:
  airflow-task-runner:
    image: airflow-runner:local
    build: ./include/airflow_task_runner
    environment:
      PYTHONUNBUFFERED: 1
    # volumes:
    # - ${PWD}/include/airflow_task_runner/xcom:/xcom
    # - ${PWD}/include/airflow_task_runner/src:/app
    networks:
      - airflow
    ports:
    - 8001:8001